name: Opendata Update
on:
  workflow_dispatch:
  schedule:
    - cron: '58 * * * *'
jobs:
  fetch-and-analyze:
    name: Run MATLAB Script
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Tokyo'
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: Run MATLAB Script
        uses: matlab-actions/run-command@v1
        with:
          command: addpath("scripts"), datawrangle;
      - name: Format JSON
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: yarn install
      - run: yarn run prettier --write ./json/       
      - name: Commit files
        run: |
          git config --local user.email ${{ secrets.EMAIL }}
          git config --local user.name "kohei ikeda"
          git status | grep modified && git commit -m "data update(`date +%Y/%m/%d`)" -a || true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
